Blockdevice stats devicemapper
prometheus/procfs pull request #412
Opened 2021-09-14 23:36 UTC by ventifus

Expose block device-mapper properties. This will enable node_exporter to expose the device-mapper information in a node_disk_info metric. (PR on that to follow.)
Closes #211.

Signed-off-by: W. Andrew Denton <git@flying-snail.net>

2021-09-17 10:24 UTC, discordianfish approved these changes

2021-10-31 12:38 UTC, SuperQ commented
This needs a rebase to update the fixtures file.

2021-11-19 09:54 UTC, discordianfish commented on blockdevice/stats.go
> +	Uuid string
Use all uppercase here: https://github.com/golang/go/wiki/CodeReviewComments#initialisms

2021-11-20 10:40 UTC, SuperQ requested changes
Minor nits, otherwise LGTM.

2021-11-20 10:40 UTC, SuperQ commented on blockdevice/stats.go
> +	// files with uint64 fields
Nit
```suggestion
	// Files with uint64 fields.
```

2021-11-20 10:40 UTC, SuperQ commented on blockdevice/stats.go
> +	// files with string fields
Nit:
```suggestion
	// Files with string fields.
```

2021-12-04 00:13 UTC, ventifus commented
Alright, I've capitalized all of the "Files with" comments (there were a few existing ones too).

2021-12-06 10:45 UTC, discordianfish commented
@SuperQ PTAL

2022-01-10 13:16 UTC, ddpolyakov commented
Hi there. Waiting for this feature a lot in a new build. @SuperQ  could you please take a look?

2022-01-10 13:26 UTC, SuperQ approved these changes
LGTM, Thanks!

2022-01-10 13:26 UTC, merged