fix bug when /proc/net/dev contains unexpected line
prometheus/procfs pull request #421
Opened 2021-11-11 11:08 UTC by bo-er

In centos 8(4.18.0-193.28.1.el8_2.x86_64) if I try this command:
```
ip link add team0:1 type dummy
```
I will get a message: 
```
"RTNETLINK answers: Invalid argument". 

```
However if I do the same thing on Centos 7(3.10.0-862.14.4.el7.x86_64), there is no error ! And If I cat /proc/net/dev I can see there is a sub interface:
```
Inter-|   Receive                                                |  Transmit
 face |bytes    packets errs drop fifo frame compressed multicast|bytes    packets errs drop fifo colls carrier compressed
  eth0: 2489766199  690315    0    0    0     0          0         0 96022876  713917    0    0    0     0       0          0
    lo: 402582904  916378    0    0    0     0          0         0 402582904  916378    0    0    0     0       0          0
team0:1:       0       0    0    0    0     0          0         0        0       0    0    0    0     0       0          0
```
So the problem is currently 'procfs' cann't parse /proc/net/dev that contains odd line of interfaces.

2021-11-12 10:42 UTC, discordianfish commented
Interesting.. well the actual problem is that this assumes a device name can't include `:`: https://github.com/prometheus/procfs/pull/421/files#diff-a691799f566ae988549d796fb8df91095344d63552424e79c7687a14dcaaf601R92

But we shouldn't just ignore parse errors. Instead, if we want to fix that, we need to parse this differently.

2021-11-12 10:43 UTC, discordianfish requested changes
Interesting.. well the actual problem is that this assumes a device name can't include `:`:  https://github.com/prometheus/procfs/pull/421/files#diff-a691799f566ae988549d796fb8df91095344d63552424e79c7687a14dcaaf601R92

But we shouldn't just ignore parse errors. Instead, if we want to fix that, we need to parse this differently.

2021-11-15 09:51 UTC, discordianfish commented
Thanks! Can you also add test cases for dev names that include :?

2021-11-21 13:05 UTC, bo-er commented
@discordianfish hello! 🙇🏻‍♂️ Do I need to add more test cases?

2021-11-21 16:00 UTC, discordianfish approved these changes
LGTM, thanks!

2021-11-21 16:01 UTC, discordianfish commented
you need to sign your commit though before we can merge. See the DCO check

2021-11-23 03:47 UTC, bo-er commented
> you need to sign your commit though before we can merge. See the DCO check

I have signed my commits.

2021-11-23 07:48 UTC, SuperQ commented
We should probably fix this the same way we fixed it in the node_exporter. I forgot we have yet to convert the node_exporter to this parser.

https://github.com/prometheus/node_exporter/pull/904
https://github.com/prometheus/node_exporter/pull/910

2021-11-23 14:23 UTC, SuperQ approved these changes
Actually, I like this better, it avoids use of regexp.

2021-11-24 21:38 UTC, merged