return error if cpufreq's are empty
prometheus/procfs pull request #426
Opened 2021-12-11 09:58 UTC by binjip978

Signed-off-by: Sergei Semenchuk <pdp.eleven11@gmail.com>

2021-12-11 10:00 UTC, binjip978 commented
fixes https://github.com/prometheus/node_exporter/issues/2198 when collector successful but empty

2022-12-17 20:00 UTC, SuperQ requested changes

2022-12-21 14:01 UTC, discordianfish commented on sysfs/system_cpu.go
> +		return nil, fmt.Errorf("could not find any cpufreq files")
Maybe `return fmt.Errorf("could not find any cpufreq files: %w", os.ErrNotExist)`?

2022-12-22 10:30 UTC, SuperQ approved these changes

2022-12-22 10:31 UTC, merged