add /proc/interrupts
prometheus/procfs pull request #475
Opened 2022-11-02 10:03 UTC by Dentrax

Signed-off-by: Furkan <furkan.turkal@trendyol.com>

I have some use-cases for this implementation:
* want to parse my `/proc/interrupts` file using procfs package (with go:linkname)
* move interrupt parsing logic [from node_exporter](https://github.com/prometheus/node_exporter/blob/68a6c78c0d1fd7359fa15d30b607b322eb512a8d/collector/interrupts_linux.go#L68-L99) to here
* also supports single values

All tests passes.

2022-11-02 19:07 UTC, Dentrax commented
I was manually update the fixture so it fails. Now just followed [Updating Test Fixtures](https://github.com/prometheus/procfs#updating-test-fixtures) instructions but I couldn't get exactly:

```
$ make fixtures/.unpacked
make: *** No rule to make target `fixtures/.unpacked'.  Stop.
```

```
$ make test
>> extracting fixtures testdata/fixtures
./ttar -C testdata/ -x -f testdata/fixtures.ttar
WARNING sed unable to handle null bytes, using Python (slow).
```

I almost waited ~5-10m but nothing happens, the process hangs, I guess. (macOS)

Feel free to commit my branch to update fixture!

2022-11-03 12:21 UTC, discordianfish commented on proc_interrupts.go
> +		if len(parts) == 0 { // skip empty lines
Same here, check if enough fields are present

2022-11-03 12:37 UTC, Dentrax commented on proc_interrupts.go
> +		if len(parts) == 0 { // skip empty lines
Done!

2022-11-08 14:53 UTC, discordianfish approved these changes
LGTM

2022-12-17 19:25 UTC, SuperQ approved these changes
Minor nit about copyright dates. Otherwise LGTM.

2022-12-17 19:25 UTC, SuperQ commented on proc_interrupts.go
> +// Copyright 2018 The Prometheus Authors
```suggestion
// Copyright 2022 The Prometheus Authors
```

2022-12-17 19:25 UTC, SuperQ commented on proc_interrupts_test.go
> +// Copyright 2020 The Prometheus Authors
```suggestion
// Copyright 2022 The Prometheus Authors
```

2022-12-17 19:26 UTC, SuperQ requested changes
Just need to update the dates.

2022-12-17 20:54 UTC, Dentrax commented
> Just need to update the dates.

Done!

2022-12-17 21:05 UTC, SuperQ approved these changes

2022-12-17 21:05 UTC, merged