Add support for thread data parsing.
prometheus/procfs pull request #481
Opened 2022-11-16 22:35 UTC by emypar

Provide access to /proc/PID/task/TID files, for thread specific values. Since such files have the same structure as /proc/PID/ ones, the data structures and the parsers for the latter may be reused.

2022-11-21 23:34 UTC, emypar commented
Hello @discordianfish, could you take a look at this simple PR? Thank you!

2022-12-13 12:29 UTC, discordianfish approved these changes
Great, LGTM!

2022-12-15 23:34 UTC, emypar commented
> Great, LGTM!

Thank you, could you also merge it on my behalf or point me to ppl. that might be able to do so? I don't have write access.

2022-12-17 14:46 UTC, discordianfish commented
We need another maintaoner to approve /cc @pgier @SuperQ

2022-12-17 16:07 UTC, SuperQ requested changes
Minor nit, otherwise LGTM.

2022-12-17 16:07 UTC, SuperQ commented on thread.go
> +// Copyright 2018 The Prometheus Authors
```suggestion
// Copyright 2022 The Prometheus Authors
```

2022-12-17 16:07 UTC, SuperQ commented on thread_test.go
> +// Copyright 2018 The Prometheus Authors
```suggestion
// Copyright 2022 The Prometheus Authors
```

2022-12-17 18:09 UTC, emypar commented on thread.go
> +// Copyright 2018 The Prometheus Authors
Done

2022-12-17 18:09 UTC, emypar commented on thread_test.go
> +// Copyright 2018 The Prometheus Authors
Done

2022-12-17 18:10 UTC, emypar commented
> Minor nit, otherwise LGTM.

Thank you, all done!

2022-12-17 19:16 UTC, SuperQ approved these changes

2022-12-17 19:18 UTC, merged

2022-12-19 23:03 UTC, emypar commented
Thank you all for making this happen.