Unify error messages and prepare to adopt wrapping error messages, part 1
prometheus/procfs pull request #518
Opened 2023-05-11 15:37 UTC by conallob

Unify error messages by using the errors module. Prepare for wrapping errors once Go v1.20 is the default.

This is part 1 of an implementation for #358

2023-05-11 18:45 UTC, SuperQ commented
This needs a DCO sign-off. You can use `git commit -s --amend` to add it.

2023-05-12 21:50 UTC, SuperQ commented on loadavg.go
> +		return nil, fmt.Errorf("%w: Malformed line %q: %w", ErrFileParse, string(loadavgBytes), err)
```suggestion
		return nil, fmt.Errorf("%w: Malformed line, too few fields in loadavg string: %q", ErrFileParse, string(loadavgBytes))
```

2023-05-12 21:51 UTC, SuperQ commented on mdstat.go
> +// Copyright 2018 The Prometheur Authors
derp

2023-05-13 00:06 UTC, conallob reviewed
I now believe the test failures are related to the golang version of the test environment.

Per https://go.dev/doc/go1.20#errors , multiple %w atoms requires Go >v1.20.x

2023-05-13 12:31 UTC, SuperQ commented
Yes, I guess we need to either string some errors, or wait a bit. We typically try and support the currently supported Go versions. So we need to stay compatible with 1.19 for now.

2023-05-13 13:04 UTC, conallob commented
I could adapt this PR to use https://github.com/hashicorp/go-multierror instead and file a new issue to migrate to the errors package once Go v1.20 is the default

2023-05-13 13:33 UTC, SuperQ commented
No, I think just using some `%s` is fine for now. For cases where there is multi-error, prefer to pass the underlying error, not the new error type.

2023-05-15 12:42 UTC, conallob commented
> No, I think just using some `%s` is fine for now. For cases where there is multi-error, prefer to pass the underlying error, not the new error type.

Done.


I've also filed https://github.com/prometheus/procfs/issues/519 to track replacing these `%s` with `%w` again, once Go v1.20 is the default

2023-05-15 13:05 UTC, SuperQ commented on fscache.go
> +			return nil, fmt.Errorf("%w: %q", ErrFileParse, s.Text())
I wonder if we should keep some of these details.

```suggestion
			return nil, fmt.Errorf("%w: malformed Fscacheinfo line: %q", ErrFileParse, s.Text())
```

2023-05-16 08:57 UTC, SuperQ approved these changes

2023-05-16 16:00 UTC, conallob commented
https://github.com/prometheus/procfs/pull/522 was intended to be a complimentary PR, but I managed to goof the git branches, so all changes are now in this PR


PTAL

2023-05-18 09:31 UTC, SuperQ requested changes
There are still a lot of errors that drop the original context of what part of parsing failed. Please make sure that we keep the original details of the parsing error intact.

I've highlighted a number of them.

2023-05-18 09:31 UTC, SuperQ commented on arp.go
> +				return []ARPEntry{}, fmt.Errorf("%s: %v: %w", ErrFileParse, entry, err)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on buddyinfo.go
> +			return nil, fmt.Errorf("%w: %v", ErrFileParse, parts)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on buddyinfo.go
> +				return nil, fmt.Errorf("%s: %f: %w", ErrFileParse, sizes[i], err)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on crypto.go
> +			return nil, fmt.Errorf("%w: %q", ErrFileParse, text)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on fscache.go
> +		return fmt.Errorf("%s: Expected %d, but got %d: %w", ErrFileParse, len(setFields), len(fields), err)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on loadavg.go
> +			return nil, fmt.Errorf("%s: %f: %w", ErrFileParse, loads[i], err)
Keep original details.

2023-05-18 09:31 UTC, SuperQ commented on mdstat.go
> +		return nil, fmt.Errorf("%s: %v: %w", ErrFileParse, fs.proc.Path("mdstat"), err)
Keep original details.

2023-05-18 09:37 UTC, conallob commented
Thanks, I have been fixing up entries that didn't give specifics, but I may have missed a few early on

2023-05-19 14:32 UTC, conallob commented
Fixed up all the vague, non specific errors (`grep "fmt.Errorf" *.go | grep -e "%s: %.: %w"` confirms they're all gone)

I do have 2 commits which aren't DCO signed (should work out how to config that per repository) and I'm not sure how to amend those commits

2023-05-23 13:20 UTC, closed without merging

2023-05-23 13:29 UTC, conallob commented
Recreated as https://github.com/prometheus/procfs/pull/526 , but without all the messed up git history