fs: Statfs_t{} doesn't have a Type field on NetBSD, OpenBSD, or Solaris
prometheus/procfs pull request #523
Opened 2023-05-17 21:23 UTC by dcbw

Other projects that import procfs, like node_exporter, apparently build for OSs that don't have Statfs_t.Type.

Leads to errors like (for node_exporter):

```
/go/bin/promu --config .promu.yml build --prefix .build/openbsd-amd64 
 >   node_exporter
# github.com/prometheus/procfs
/go/pkg/mod/github.com/prometheus/procfs@v0.9.1-0.20230517120836-7acd99d0499a/fs.go:63:14: stat.Type undefined (type syscall.Statfs_t has no field or method Type)
!! command failed: build -o .build/openbsd-amd64/node_exporter -ldflags -X github.com/prometheus/common/version.Version=1.5.0 -X github.com/prometheus/common/version.Revision=849b6076b81bf64249b4f75e0c3134d25a1da9a3 -X github.com/prometheus/common/version.Branch=pull/2669 -X github.com/prometheus/common/version.BuildUser=root@d9577d73a62f -X github.com/prometheus/common/version.BuildDate=20230517-20:49:53  -extldflags '-static' -a -tags 'netgo osusergo static_build' github.com/prometheus/node_exporter: exit status 1
```

2023-05-17 21:24 UTC, dcbw commented
See https://app.circleci.com/pipelines/github/prometheus/node_exporter/3445/workflows/1ca8faff-eabc-45fd-a7f1-0b07dffd6569/jobs/18019 for the full  node_exporter CI failure

2023-05-20 12:26 UTC, discordianfish approved these changes
Good catch, thanks!

2023-05-20 13:50 UTC, SuperQ requested changes
The convention for naming these files would be `fs_linux.go` and `fs_others.go`, see how the naming and tags are done for `cpuinfo*.go`.

2023-05-20 13:57 UTC, SuperQ approved these changes
On second thought, this is fine.

2023-05-20 13:57 UTC, merged

2023-05-22 01:50 UTC, dcbw commented
@SuperQ I thought about that, but given that FreeBSD/Darwin also have Type, and at least FreeBSD can emulate Linux procfs with the same magic as Linux, didn't seem quite right to make it _linux.go.