enhancement: Use pointer fields for `FibreChannel*`
prometheus/procfs pull request #623
Opened 2024-03-23 00:34 UTC by rexagod

Allow fields to be `nil`-checked.

Fixes: #612

PS. This is a **breaking** change.
***

@machine424 I took the liberty of sending out a PR targeting this issue, but please feel free to close this if you already have a patch on the way. :)

2024-03-23 10:55 UTC, discordianfish approved these changes
Makes sense

2024-03-23 16:40 UTC, SuperQ requested changes

2024-03-23 16:40 UTC, SuperQ commented on sysfs/class_fibrechannel_test.go
> +	"k8s.io/utils/ptr"
While this is a convenient package, I'm not sure we want to add this to the dependency tree.

This package is pulled in by a lot of places and I would like to minimize the indirect requirements.

In other similar tests, it's painful, but we do string vars and then `&stringVar`.

2024-04-10 11:45 UTC, discordianfish commented
@SuperQ PTAL

2024-05-12 16:29 UTC, SuperQ approved these changes

2024-05-12 16:30 UTC, merged